### ISSUE TITLE
Import of CSARs in Safari not possible

### ISSUE THREAD

**Issue by fakepk** [OpenTOSCA/winery#1]
In Safari (tested version 10.1.1 (12603.2.4)) CSARs can not be selected in the **Upload CSAR** dialogue.

To reproduce navigate to `/winery/servicetemplates/ --> Import CSAR --> Select File`. Here CSARs are listed but not selectable.

**Comment by koppor** [comment]
Currently supported on Firefox and Chrome

**Comment by miwurster** [comment]
Safari not supported
