### ISSUE TITLE
Winery generates (maybe) wrong repository if generating IAs

### ISSUE THREAD

**Issue by udschaman** [OpenTOSCA/winery#115]
After the generation of an IA in Winery, the generated POM uses this repository for Winary-Libs:
```
<repositories>
        <repository>
            <id>opentosca</id>
            <url>https://opentosca.github.io/mvn-repo/</url>
        </repository>
</repositories>
```
from which Maven isn't able to download/import the libs.

Using the repository titled in Github:
```
<repositories>
        <repository>
            <id>opentosca-mvn-repo</id>
            <url>https://raw.github.com/OpenTOSCA/mvn-repo/ustutt/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
</repositories>
```
solves the Maven import problem.

Was the repository relocated, but this information isn't set in the generation of the POMs of the IAs?

**Comment by miwurster** [comment]
That doesn't seem to be an issue anymore.
