### ISSUE TITLE
Check for namespace name conventions

### ISSUE THREAD

**Issue by koppor** [OpenTOSCA/winery#12]
An organization might agree that their namespaces do not end with `/`. This should be checked.

- [ ] Configurable rules (e..g, prefix www.example.com/winery should never end with `/`)
- [x] Checker at the repository
- [ ] Creation at the UI should be forbidden

**Comment by shashi-rks** [comment]
Hello, I recently installed winery with steps mentioned in InstallationGuide.pdf from OPenTOSCA website. Using Tomcat server, it was installed and I can see page http://x.x.x.x:8080/winery/servicetemplates/. But as I was trying to add artifact type, it always gave me error "Could not add Artifact Type". I tried using various namespaces as mentioned in InstallationGuide.pdf file but it failed every time. Can you please help me here?

**Comment by koppor** [comment]
Refs https://github.com/OpenTOSCA/winery/issues/90

**Comment by miwurster** [comment]
That doesn't seem to be an issue anymore.
