### ISSUE TITLE
[Topology Modler] Can't add NodeType after save.

### ISSUE THREAD

**Issue by jsvde** [OpenTOSCA/winery#125]
When a ServiceTemplate is opened in the Topology Modler, NodeTypes can be added to topology.
After the save button is pressed this is not possible anymore.
Trying to drag a NodeType results in following error:

`ERROR TypeError: Cannot read property 'color' of undefined`  by `app/palette/palette.component.ts`

This can be circumvented by saving and just refreshing the window.
Can somebody reproduce or did encounter this error before?

Browser: Chrome 69.0.3497.100
OS: macOS Sierra 10.12

**Comment by ledicjp** [comment]
This might have the same cause as the `cannot read property 'type' of undefined` Errors I keep getting.

The server logs look like this:
https://gist.github.com/ledicjp/62f391de782a729d7c605ca0bfce1271

**Comment by miwurster** [comment]
That doesn't seem to be an issue anymore.
