### ISSUE TITLE
Creation of Duplicate folders in Artifacts

### ISSUE THREAD

**Issue by SainiNidhi** [OpenTOSCA/winery#126]
Whenever I upload any CSAR and download it after some changes, duplicate folders are created inside all the components in artifacts.

For eg. 

/artifacttemplates/http%3A%2F%2Fopentosca.org%2Fartifacttemplates/Container_DA/files/artifacttemplates/http%3A%2F%2Fopentosca.org%2Fartifacttemplates/Container_DA/files/ 

I have tried downloading CSAR from Topology template or Service template.

Browser: Chrome Version 65.0.3325.181 
OS: Ubuntu 16.04 LTS

**Comment by koppor** [comment]
@SainiNidhi Thank you for the report! You would help us diving into the issue if you wrote some import/export tests as asked for at https://github.com/eclipse/winery/pull/265#issuecomment-395400048.

**Comment by SainiNidhi** [comment]
Hello, is there any update for this issue. I recently checked it, there are still duplicate folders creating.

**Comment by v-yussupov** [comment]
@SainiNidhi could you provide us with more context? which branch are you working on, have you tried it with one particular csar or any csar gives you the same result, etc? 
also, it would be nice if you describe the steps needed to reproduce this problem, e.g., 
step1: export csar, 
step2: ...

**Comment by miwurster** [comment]
Seems no longer relevant.
