### ISSUE TITLE
npm package @winery/topologymodeler fails to run in angular app

### ISSUE THREAD

**Issue by Jojo134** [OpenTOSCA/winery#128]
ERROR in node_modules/@winery/topologymodeler/src/app/refinementSidebar/refinementWebSocket.service.d.ts(38,31): error TS2307: Cannot find module '../../../../../../../Users/Josip/winery/org.eclipse.winery.topologymodeler.ui/node_modules/rxjs/internal/Observable'.

**Comment by miwurster** [comment]
That doesn't seem to be an issue anymore.
