### ISSUE TITLE
Winery Handles Properties and PropertyMappings Vaguely

### ISSUE THREAD

**Issue by ghareeb-falazi** [OpenTOSCA/winery#134]
## Before I added this bug/feature request I checked these

* [x] This issue/feature is not reported yet 
* [x] I built the project based on the latest master
* [x] I have checked the documentation to see if there is a procedure described for this case

## Affected components

* [x] Winery
  * [ ] Backend
  * [x] Management UI
  * [ ] Topology Modeler
  * [ ] Workflow Modeler
* [ ] Container
* [ ] OpenTOSCA UI
* [ ] TOSCA-Definitions
   * [ ] https://github.com/OpenTOSCA/tosca-definitions-internal
   * [ ] https://github.com/OpenTOSCA/tosca-definitions-public
   * [ ] https://github.com/winery/test-repository
   * [ ] https://github.com/winery/test-repository-yaml
* [ ] docker-compose file
* [ ] container-client
* [ ] opentosca-website

## My environment

- operating system (+ version): Windows 10 Pro

## Expected behaviour
- When specifying a service template property mapping in the boundary definitions tab, it should be clear that an XPath should be specified as a **Property Name** instead of a simple name OR a suitable XPath is generated.
- When specifying service template properties in the boundary definitions tab, there is an option to create a simple key-value list of properties, or a complex XML document.
## Actual behaviour [in case of an issue]
- Generated PropertyMapping has a faulty/vague `serviceTemplatePropertyRef` value (should be an XPath to the property, but rather is just the property name)
- Properties are an xml document and no option for a key-value pair list exists.

## How can the issue be reproduced [in case of an issue]?
Go to any service template in winery -> BoundaryDefinitions -> PropertyMappings -> create a new property mapping based on a node template property -> check the generated xml

![image](https://user-images.githubusercontent.com/28387669/57232713-78873480-701d-11e9-9522-b787ee531b1d.png)
![image](https://user-images.githubusercontent.com/28387669/57234582-41b31d80-7021-11e9-8132-8d52625f3c48.png)

**Comment by ghareeb-falazi** [comment]
refers to https://github.com/OpenTOSCA/winery/issues/13 and to https://github.com/koppor/heuhaufen/issues/199

**Comment by miwurster** [comment]
That doesn't seem to be an issue anymore.
