### ISSUE TITLE
Fix instantiateRelationshipTemplate

### ISSUE THREAD

**Issue by koppor** [OpenTOSCA/winery#14]
@hirmerpl - in Winery lassen sich manuell (also über den XML-Editor der Weboberfläche) keine UUIDs bei den ID-Feldern eintragen (da kein NCName). Die Helper-Methoden in den ModelUtilities von Winery Common instantiateNodeTemplate und instantiateRelationshipTemplate generieren aber solche UUIDs und lassen sich wohl auch abspeichern ohne dass es einen Fehler gibt.

- [ ] check, where this method is used
- [ ] fix

**Comment by miwurster** [comment]
Seems no longer relevant.
