### ISSUE TITLE
How to define Constraints for the Properties

### ISSUE THREAD

**Issue by AmitSharma68** [OpenTOSCA/winery#142]

**Comment by AmitSharma68** [comment]
Is there a way we can enforce constraints (defined in TOSCA simple profile v1.2) on properties defined corresponding to TOSCA Contructs? Also is there a way to define custom constraints (using java script, groovy or python) and associate the same to the node type properties?

**Comment by miwurster** [comment]
Custom constraints are not supported and never will be. Simple constraints are now available (see `project/radon` branch).
