### ISSUE TITLE
Stoppping and restarting Winery as a docker container fails with git repository

### ISSUE THREAD

**Issue by nyuuyn** [OpenTOSCA/winery#149]
Stoppping and Restarting winery as a docker container fails when a git repository is cloned into the container.
This is because when you initially create the container it clones it:

`CMD dockerize -template /root/.winery/winery.yml.tpl:/root/.winery/winery.yml \
    && if [ ! "x${WINERY_REPOSITORY_URL}" = "x" ]; then git clone ${WINERY_REPOSITORY_URL} ${WINERY_REPOSITORY_PATH}; else git init $WINERY_REPOSITORY_PATH; fi \
    && cd ${WINERY_REPOSITORY_PATH} \
    && git config --global core.fscache true \
    && git lfs install \
    && echo 'export CATALINA_OPTS="-Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx${WINERY_HEAP_MAX} -XX:MaxPermSize=256m"' > ${CATALINA_HOME}/bin/setenv.sh \
    && if [ ! "x${WINERY_JMX_ENABLED}" = "x" ]; then echo 'export CATALINA_OPTS="${CATALINA_OPTS} -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.ssl=false"' >> ${CATALINA_HOME}/bin/setenv.sh; fi \
    && chmod a+x ${CATALINA_HOME}/bin/setenv.sh \
    && ${CATALINA_HOME}/bin/catalina.sh run`

And when you restart it, it wants to clone again, but the local repository is already initialized, and therefore the restart fails because of the wrong error code returned by git:

`17-Oct-2019 14:53:39.848 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
17-Oct-2019 14:53:39.851 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 7728 ms
fatal: destination path '/var/opentosca/repository' already exists and is not an empty directory.`

Possible workaround:
check if git repo is already there, if not clone, if yes pull

**Comment by miwurster** [comment]
Fixed in master.
