### ISSUE TITLE
Authors are not properly serialized to self-service meta data json

### ISSUE THREAD

**Issue by fakepk** [OpenTOSCA/winery#2]
```xml
<ns6:authors>IAAS, University of Stuttgart</ns6:authors>
```

is serialized to

```json
"authors": [
        "IAAS,",
        "University",
        "of",
        "Stuttgart"
    ]
```

**Comment by koppor** [comment]
IMHO Winery should not create data.json in the CSAR at all as data.json is sent by the Container to the UI, isn't it?

**Comment by fakepk** [comment]
You are right, so I will create a new feature request for the container API.

Let's close this issue here!

**Comment by koppor** [comment]
- Winery does not export and import data.json any more.
- https://github.com/eclipse/winery/blob/master/org.eclipse.winery.model.selfservice/src/main/resources/SelfServiceModel.xsd#L32 should be updated.
