### ISSUE TITLE
Dialog "Add Implementation Artifact" field inserts curly brackets in default value

### ISSUE THREAD

**Issue by FlxB2** [OpenTOSCA/winery#201]
When using the XML Format the dialog found in

Node Type Implementation -> Implementation Artifacts -> Add Implementation Artifact

is broken. The field "Name" in the form group "Artifact Template Creation" inserts "{ }" brackets around the default value. This breaks all links relating to this element.

Image: 
![issue](https://user-images.githubusercontent.com/7521847/83334499-39222a80-a2a7-11ea-9dc8-2cf7e6393649.jpg)

**Comment by Legion2** [comment]
Also this Implementation Artifacts can not be deleted in the UI because when clicking on it's entry the URL is broken

**Comment by lharzenetter** [comment]
This issues seems to be resolved.
