### ISSUE TITLE
InputParamters Invalid When Importing a CSAR

### ISSUE THREAD

**Issue by lharzenetter** [OpenTOSCA/winery#232]
After I imported a CSAR, the Node Type definitions are corrput:

```xml
<Operation name="configure">
    <InputParameters>
        <InputParameter name="DBMSUser" type="xsd:string" required="false"/>
        <InputParameter name="DBMSPassword" type="xsd:string" required="false"/>
        <InputParameter name="DBMSPort" type="xsd:string" required="false"/>
    </InputParameters>
</Operation>
```

`required="false"` in this case was even wrong, as it was set to `yes` in the CSAR.

The requried flag is a [TBoolean](https://github.com/OpenTOSCA/winery/blob/ustutt/org.eclipse.winery.model/org.eclipse.winery.model.tosca.xml/src/main/java/org/eclipse/winery/model/tosca/xml/XTBoolean.java) and must be either saved as `yes` or `no`.

**Comment by mar-be** [comment]
Fixed in https://github.com/eclipse/winery/pull/606
