### ISSUE TITLE
Elements Are Displayed Multiple Times

### ISSUE THREAD

**Issue by lharzenetter** [OpenTOSCA/winery#234]
In some cases Node Types are shown multpile times. This is not supposed to happen. 

Occurred using the [example applications repo](https://github.com/OpenTOSCA/tosca-definitions-example-applications).

![image](https://user-images.githubusercontent.com/23058331/117667940-bcc9e400-b1a5-11eb-8c16-a8f70fcc77d7.png)

**Comment by mar-be** [comment]
Fixed in https://github.com/eclipse/winery/pull/605
