### ISSUE TITLE
Artifact files exported in wrong path

### ISSUE THREAD

**Issue by ana-silva** [OpenTOSCA/winery#53]
Currently (commit b384ec7), artifact files (e.g., tinytodo.zip) are exported in the wrong path, two folder hierarchy levels too deep:

**as-is**: MyTinyToDo_Bare_Docker.csar\artifacttemplates\http%3A%2F%2Fopentosca.org%2Fartifacttemplates\MyTinyToDo_DA\files\ \ \tinytodo.zip

**should-be**: MyTinyToDo_Bare_Docker.csar\artifacttemplates\http%3A%2F%2Fopentosca.org%2Fartifacttemplates\MyTinyToDo_DA\files\tinytodo.zip

**Comment by koppor** [comment]
This should be fixed at https://github.com/OpenTOSCA/winery/commit/0b5806b978319d6fb37bc184043dc4cc22801a0d#diff-af1c97e5277091156ff419bb861462bd, also including a test case https://github.com/OpenTOSCA/winery/commit/0b5806b978319d6fb37bc184043dc4cc22801a0d#diff-d53ad573f1eeb276b41b5fd38a0a9ed3.

Please check whether it works.

**Comment by ana-silva** [comment]
It works.
