### ISSUE TITLE
Fehlerhafte URL-Enkodierung bei Klick auf "Edit"

### ISSUE THREAD

**Issue by matejetz** [OpenTOSCA/winery#63]
Vergleiche via Klick auf "Edit":

http://192.168.99.100:8080/#/servicetemplates/http%25253A%25252F%25252Fopentosca.org%25252Fservicetemplates/Apache-Spark-App_On_VSphere/readme

und direkt: 
http://192.168.99.100:8080/#/servicetemplates/http%253A%252F%252Fopentosca.org%252Fservicetemplates/Apache-Spark-App_On_VSphere/readme

Das führt dazu, dass einige Menüpunkte, wie z.B. "Plans", eine 404 OK(?)-Fehlermeldung anzeigen anstatt des eigentlichen Contents.

**Comment by lharzenetter** [comment]
fixed with: https://github.com/OpenTOSCA/winery/commit/2cd69956f35d86f5e5482e689486a4fede4ffd7c
