### ISSUE TITLE
Rework example for topology completion

### ISSUE THREAD

**Issue by koppor** [OpenTOSCA/winery#8]
The example repository https://wiki.eclipse.org/File:Tc_demo_repository.zip uses requirement types in the namespace `http://www.w3.org/2001/XMLSchema`, which is not a namespace treated by OpenTOSCA or Eclipse Winery. It is referenced from http://eclipse.github.io/winery/user/TopologyCompletionTutorial.

The example should be reworked to use available types in https://github.com/winery/test-repository

**Comment by miwurster** [comment]
Seems no longer relevant.
