### ISSUE TITLE
Incompatibilities between old and new topologymodeler

### ISSUE THREAD

**Issue by adrianwersching** [OpenTOSCA/winery#80]
Old topology modeler

```xml
<NodeTemplate winery:location="Provider">
<RelationshipTemplate xmlns:ponyuniverse="http://winery.opentosca.org/test/ponyuniverse"
                      type="ponyuniverse:standsOn">
```

New topology modeler

```xml
<NodeTemplate location="Provider">
<ns5:RelationshipTemplate xmlns:ns5="http://docs.oasis-open.org/tosca/ns/2011/12"
                          xmlns="" type="standsOn">
```

- winery:location is now location, winery extension namespace missing in new topology modeler?
- only local name of Relationship Template type in new topology modeler included -> complete type QName not present when accessing TRelationshipTemplate in backend

**Comment by ledicjp** [comment]
We can't reproduce the issue with the locations, all attributes at "otherAttributes" (i.e., x, y, location) get the "winery:" prefix correctly in the XML representation.
The issue with the RelationshipTemplates is known and our primary focus atm.

**Comment by adrianwersching** [comment]
On my machine I can do the following:

1. Add new Node Template
2. Set location -> XML only contains "location" witout prefix
3. Reload topologymodeler
4. Save topology again -> XML now has correct "winery:location"

"x" and "y" are prefixed wih "winery:" right from the start.
