### ISSUE TITLE
CSAR export broken

### ISSUE THREAD

**Issue by koppor** [OpenTOSCA/winery#9]
Currently, the CSAR export runs through, but the ZIP cannot be opened.

**Comment by koppor** [comment]
Rumors say that it has something todo with properties.

**Comment by nyuuyn** [comment]
We found out yesterday that the ArtifactReference element is missing in the ArtifactTemplate Definition (Try it out by exporting mytinytodo_bare_docker from tosca definitions).

Interestingly, last week only the concrete file (tinytodo.zip) was missing and not the ArtifactReference

**Comment by ana-silva** [comment]
Currently (commit b384ec7e), artifacts files (e.g., tinytodo.zip) are exported in the wrong path:

**as-is**:  MyTinyToDo_Bare_Docker.csar\artifacttemplates\http%3A%2F%2Fopentosca.org%2Fartifacttemplates\MyTinyToDo_DA\files\ \ \tinytodo.zip

**should-be**: MyTinyToDo_Bare_Docker.csar\artifacttemplates\http%3A%2F%2Fopentosca.org%2Fartifacttemplates\MyTinyToDo_DA\files\tinytodo.zip
